### PR TITLE
ADD ANIMATION 

### PR DESCRIPTION
**Pull request by soxmonitor**

### CODE REVIEW

**Comment by soxmonitor** [comment]
Go ahead

**Comment by HillCao02** [comment]
Good

**Comment by soxmonitor** [comment]
This is the combat animations made by Unity 3D, they are used for visualizing the battle results. By watching the combat animation, players can be easily acknowledged the results and make the decision for next step.

**Comment by HillCao02** [comment]
Excellent implementation of adding animation, by watching the animation, players can quickly realize the results and make the decision, by doing this, players would have an immersed sense of lying down on a battlefield field with tar, body, and crater, taking responsibility for every strategy made.

**Comment by Brian031205** [comment]
Fantastic and well-considered battle animation and images, it gives a sense of thrilling and excitement to the players that play our game. Changes like this is very necessary since our game is a tactical duel game and a nice picture and a good animation would bring the game to an upper level.

**Pull request closed without merging**
